### ISSUE TITLE
Duplication of definitions of RequestBlockRoot ,RequestBlockHeader and RequestBlockBody

### ISSUE THREAD

**Issue by Mikerah** [Whiteblock/hobbits#26]
I noticed that `REQUEST_BLOCK_ROOT`, `REQUEST_BLOCK_HEADER` and `REQUEST_BLOCK_BODY` have the same definitions. 

Is there any rationale for this or is it a mistake?

For reference:
`REQUEST_BLOCK_ROOT`: https://github.com/Whiteblock/hobbits/blob/master/messages.md#0x10-request_block_root

`REQUEST_BLOCK_HEADER`: https://github.com/Whiteblock/hobbits/blob/master/messages.md#0x12-request_block_header

`REQUEST_BLOCK_BODY`: https://github.com/Whiteblock/hobbits/blob/master/messages.md#0x14-request_block_body

**Comment by zscole** [comment]
Ah, yeah, I didn't even notice this. It was taken from the spec. Thanks for bringing it up. I think it would make more sense to add a field which indicates that the type of message is a request. What do you think?
 
EDIT:
On second though, I don't think this would be entirely necessary since the message type itself would indicate that it's a request. It may appear to be a duplicate, but when I receive it, I know based on the message type that this is a request for the block body indicated by these fields.

**Comment by Mikerah** [comment]
Since `REQUEST_BLOCK_ROOT`, `REQUEST_BLOCK_HEADER` and `REQUEST_BLOCK_BODY` share the same message bodies but different codes, we end up having to handle multiple messages that aren't different. Why do this when we can just have a field that indicates what we are requesting? Then, clients can perform optimizations in order to retrieve the other types of data easily. Overall, it would reduce the amount of messages necessary to handle.

**Comment by zscole** [comment]
Yes, I agree, that's what my thought was initially. I changed my mind on that because I thought it could incur additional overhead since you'd have to unmarshal the message. If you had an idea what it entailed prior, you could potentially save time by only referring to relevant messages. Now that I think about it again, that overhead should actually be negligible and that was a big consideration in our initial design. I don't think there's any practical reason why we can't condense these and add that additional field, but I'd be interested in hearing the opinions from @dreamcodez and @jrhea too just in case there's something we're not considering.

**Comment by atoulme** [comment]
They do different things - they request different types of objects.

This is now living at https://github.com/Whiteblock/hobbits/blob/master/rpc-messages.md

Does it look OK now?

**Comment by atoulme** [comment]
On using different method IDs: It's so we can easily replay messages across the network I guess.
This is also a straight copy of how LES does it, by offering requests and responses as separate IDs.

I don't think the overhead is too big. I also think you can then have partial impls where you only implement header retrieval for example.

**Comment by Mikerah** [comment]
> They do different things - they request different types of objects.

I am aware that they request different objects. However, we can reduce this to 1 message and then have an extra field indicating what is being requested. It just seems redundant to me. Other than the overhead of unmarshalling and re-marshalling, I can't think of a reason why we need 2 messages with the same definition.

**Comment by atoulme** [comment]
Yes sorry, my first response was not good. Is my second response fairing any better?

**Comment by Mikerah** [comment]
I understand your second response. I'm not sure what the best option is. We can keep it the same way or we can unmarshal and marshal accordingly.

**Comment by Mikerah** [comment]
Closing since stale.
